import { Metadata } from "next";
export const metadata: Metadata = {
  title: {
    default: "default title",
    template: "%s added template by root layout",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <ul
            style={{
              width: "100%",
              display: "flex",
              flexDirection: "row",
              gap: "50px",
            }}
          >
            <li>Home</li>
            <li>About</li>
            <li>Product</li>
            <li>Price</li>
          </ul>
        </header>
        {children}
        <footer>This is footer area</footer>
      </body>
    </html>
  );
}
